"""Business semantics boundary for configurable e-commerce data sources."""

from .errors import (
    SemanticLayerError,
    SourceConfigInactiveError,
    SourceConfigNotFoundError,
    SourceConfigRevisionConflictError,
    SourceConfigValidationError,
    SourceConfigUnverifiedError,
    SourceRecordLookupError,
    SourceValueConversionError,
    SourceDryRunError,
    SourceSchemaDriftError,
)
from .models import (
    ConnectorConfig,
    DataSourceConfig,
    FieldMapping,
    PreparedTask,
    ProductReference,
    ProductReferenceStrategy,
    ProductKey,
    SourceReceipt,
    SourceStatus,
    StandardMarketingTask,
    StandardProduct,
    TableMapping,
    TaskKey,
    normalize_source_type,
)
from .repository import LocalFileSourceConfigRepository, SourceConfigRepository
from .confirmation import (
    ConfirmationResult,
    DryRunReport,
    MappingSelection,
    compile_draft_config,
    confirm_draft_config,
    validate_draft_samples,
)
from .discovery import (
    CandidateConfidence,
    DiscoverySnapshot,
    FeishuDiscoveryClient,
    FieldMetadata,
    MappingCandidate,
    SchemaDriftReport,
    SourceRecord,
    TableMetadata,
    discover_source,
    ensure_schema_compatible,
    mapping_candidates,
    normalize_field_metadata,
    normalize_sample_records,
    normalize_table_metadata,
    schema_fingerprint,
    validate_schema_drift,
)
from .runtime import ConfiguredSourceRuntime, FeishuDataGateway
from .orchestration import ConfiguredSourceOrchestrator, DeliveryGateway

__all__ = [
    "ConnectorConfig",
    "ConfirmationResult",
    "ConfiguredSourceRuntime",
    "ConfiguredSourceOrchestrator",
    "CandidateConfidence",
    "DataSourceConfig",
    "DiscoverySnapshot",
    "DryRunReport",
    "FieldMapping",
    "FieldMetadata",
    "FeishuDiscoveryClient",
    "FeishuDataGateway",
    "DeliveryGateway",
    "LocalFileSourceConfigRepository",
    "MappingCandidate",
    "MappingSelection",
    "PreparedTask",
    "ProductReference",
    "ProductReferenceStrategy",
    "ProductKey",
    "SemanticLayerError",
    "SourceConfigInactiveError",
    "SourceConfigNotFoundError",
    "SourceConfigRepository",
    "SourceConfigRevisionConflictError",
    "SourceConfigValidationError",
    "SourceConfigUnverifiedError",
    "SourceRecordLookupError",
    "SourceDryRunError",
    "SourceReceipt",
    "SourceRecord",
    "SchemaDriftReport",
    "SourceStatus",
    "SourceValueConversionError",
    "SourceSchemaDriftError",
    "StandardMarketingTask",
    "StandardProduct",
    "TableMapping",
    "TableMetadata",
    "TaskKey",
    "normalize_source_type",
    "compile_draft_config",
    "confirm_draft_config",
    "discover_source",
    "ensure_schema_compatible",
    "mapping_candidates",
    "normalize_field_metadata",
    "normalize_sample_records",
    "normalize_table_metadata",
    "schema_fingerprint",
    "validate_draft_samples",
    "validate_schema_drift",
]
